galerija_frontend:
    resource: "@GalerijaFrontendBundle/Resources/config/routing.yml"
    prefix:   /

galerija_api:
    resource: "@GalerijaAPIBundle/Resources/config/routing.yml"
    prefix:   /
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc